/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as HelpRouteImport } from './routes/help'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices.$deviceId'
import { Route as AdminReservationsRouteImport } from './routes/admin.reservations'
import { Route as AdminPendingRouteImport } from './routes/admin.pending'
import { Route as AdminOverdueRouteImport } from './routes/admin.overdue'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'

const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/admin/reservations',
  path: '/admin/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPendingRoute = AdminPendingRouteImport.update({
  id: '/admin/pending',
  path: '/admin/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOverdueRoute = AdminOverdueRouteImport.update({
  id: '/admin/overdue',
  path: '/admin/overdue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/reservations': typeof ReservationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/overdue': typeof AdminOverdueRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/reservations': typeof ReservationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/overdue': typeof AdminOverdueRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/health': typeof HealthRoute
  '/help': typeof HelpRoute
  '/policies': typeof PoliciesRoute
  '/reservations': typeof ReservationsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/overdue': typeof AdminOverdueRoute
  '/admin/pending': typeof AdminPendingRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogue'
    | '/contact'
    | '/health'
    | '/help'
    | '/policies'
    | '/reservations'
    | '/admin/dashboard'
    | '/admin/overdue'
    | '/admin/pending'
    | '/admin/reservations'
    | '/devices/$deviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogue'
    | '/contact'
    | '/health'
    | '/help'
    | '/policies'
    | '/reservations'
    | '/admin/dashboard'
    | '/admin/overdue'
    | '/admin/pending'
    | '/admin/reservations'
    | '/devices/$deviceId'
  id:
    | '__root__'
    | '/'
    | '/catalogue'
    | '/contact'
    | '/health'
    | '/help'
    | '/policies'
    | '/reservations'
    | '/admin/dashboard'
    | '/admin/overdue'
    | '/admin/pending'
    | '/admin/reservations'
    | '/devices/$deviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  HealthRoute: typeof HealthRoute
  HelpRoute: typeof HelpRoute
  PoliciesRoute: typeof PoliciesRoute
  ReservationsRoute: typeof ReservationsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminOverdueRoute: typeof AdminOverdueRoute
  AdminPendingRoute: typeof AdminPendingRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/admin/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pending': {
      id: '/admin/pending'
      path: '/admin/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AdminPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/overdue': {
      id: '/admin/overdue'
      path: '/admin/overdue'
      fullPath: '/admin/overdue'
      preLoaderRoute: typeof AdminOverdueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  HealthRoute: HealthRoute,
  HelpRoute: HelpRoute,
  PoliciesRoute: PoliciesRoute,
  ReservationsRoute: ReservationsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminOverdueRoute: AdminOverdueRoute,
  AdminPendingRoute: AdminPendingRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
